version: 0.0
os: linux
files:
   -source: /EmpApp.py
    destination: /abbas1998khan/updatedawsproject

hooks:
  ApplicationStop:
    - location: stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_container.sh
      timeout: 300
      runas: root
      
      
