version: 9.4
os: ubuntu
files:
  - source: /EmpApp.py
    destination: /home/ubuntu/awsmatsproject
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root
